### ISSUE TITLE
Feature List

### ISSUE THREAD

**Issue by basarat** [alm-tools/alm#32]
Add to readme at some point

# Working on 

## TypeScript 

* [x] Auto detection of all available `tsconfig.json` projects + project list + project selector
* [x] Live error panel

## Code Mirror 
* [x] State synced between browser tabs 
* [x] Autocomplete 
* [x] Autocomplete docs
* [x] Live linting
* [x] Expand errors inline https://github.com/TypeScriptBuilder/tsb/issues/8
* [x] type info on hover 

## Overall 
* [x] Find in file 
* [x] Find in project / files / glob filter + replace 
* [x] Goto list (references, find etc)
* [x] rename refactoring 
* [x] File rename refactoring 
* [x] File explorer aka tree view

## Omni search 
* [x] file list 
* [x] project list 
* [x] Command list
* [x] Symbols in file search 
* [x] Symbols in project search

# Deploy

* [x] Basic compile test
* [x] Setup automatic NPM deploy on tagged versions using Travis

# TODO: 

* [x] Autocomplete snippets 
* [x] list commands supported by CM in command list

**Comment by basarat** [comment]
done :rose:
